name: osworld
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - accelerate==1.11.0
      - ag2==0.9.10
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - aistudio-sdk==0.3.8
      - alibabacloud-credentials==1.0.3
      - alibabacloud-credentials-api==1.0.0
      - alibabacloud-ecs20140526==7.2.4
      - alibabacloud-endpoint-util==0.0.4
      - alibabacloud-gateway-spi==0.0.3
      - alibabacloud-openapi-util==0.2.2
      - alibabacloud-tea==0.4.3
      - alibabacloud-tea-openapi==0.4.1
      - alibabacloud-tea-util==0.3.13
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anthropic==0.71.0
      - anyascii==0.3.3
      - anyio==4.11.0
      - apache-tvm-ffi==0.1.2
      - apscheduler==3.11.0
      - astor==0.8.1
      - async-timeout==5.0.1
      - audioread==3.1.0
      - azure-core==1.36.0
      - azure-identity==1.25.1
      - azure-mgmt-compute==37.0.1
      - azure-mgmt-core==1.6.0
      - azure-mgmt-network==30.0.0
      - backoff==2.2.1
      - bce-python-sdk==0.9.52
      - bcrypt==5.0.0
      - beautifulsoup4==4.14.2
      - blake3==1.0.8
      - borb==3.0.2
      - boto3==1.40.60
      - botocore==1.40.60
      - cachetools==6.2.1
      - cbor2==5.7.1
      - certifi==2025.11.12
      - cffi==2.0.0
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - cli-exit-tools==1.2.7
      - cloudpickle==3.1.1
      - colorlog==6.10.1
      - compressed-tensors==0.12.2
      - contourpy==1.3.2
      - cryptography==44.0.3
      - cssselect==1.3.0
      - cuda-bindings==13.0.3
      - cuda-pathfinder==1.3.2
      - cuda-python==13.0.3
      - cupy-cuda12x==13.6.0
      - cycler==0.12.1
      - darabonba-core==1.0.3
      - dashscope==1.24.8
      - decorator==5.2.1
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - depyf==0.20.0
      - dill==0.4.0
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.8.0
      - docker==7.1.0
      - docstring-parser==0.17.0
      - dotenv==0.9.9
      - easyocr==1.7.2
      - einops==0.8.1
      - email-validator==2.3.0
      - et-xmlfile==2.0.0
      - evdev==1.9.2
      - exceptiongroup==1.3.0
      - fabric==3.2.2
      - farama-notifications==0.0.4
      - fastapi==0.121.2
      - fastapi-cli==0.0.16
      - fastapi-cloud-cli==0.3.1
      - fastdtw==0.3.4
      - fastrlock==0.8.3
      - filelock==3.20.0
      - flashinfer-python==0.5.2
      - flask==3.0.3
      - fonttools==4.60.1
      - formulas==1.3.2
      - frozendict==2.4.7
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - func-timeout==4.3.5
      - future==1.0.0
      - gdown==5.2.0
      - gguf==0.17.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.27.0
      - google-api-python-client==2.185.0
      - google-auth==2.41.1
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.71.0
      - greenlet==3.2.4
      - groq==0.33.0
      - grpcio==1.76.0
      - grpcio-status==1.71.2
      - gymnasium==0.28.1
      - h5py==3.15.1
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - imagehash==4.3.2
      - imagesize==1.4.1
      - interegular==0.3.3
      - invoke==2.2.1
      - isodate==0.7.2
      - jax-jumpy==1.0.0
      - jiter==0.11.1
      - jmespath==1.0.1
      - joblib==1.5.2
      - json-minify==0.3.0
      - json-repair==0.52.3
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - langdetect==1.0.9
      - lark==1.2.2
      - lib-detect-testenv==2.0.8
      - librosa==0.11.0
      - llguidance==1.3.0
      - llvmlite==0.44.0
      - lm-format-enforcer==0.11.3
      - loguru==0.7.3
      - lxml==6.0.2
      - markupsafe==3.0.3
      - matplotlib==3.8.4
      - mistral-common==1.8.5
      - ml-dtypes==0.5.4
      - model-hosting-container-standards==0.1.9
      - modelscope==1.32.0
      - mouseinfo==0.1.3
      - mpmath==1.3.0
      - msal==1.34.0
      - msal-extensions==1.3.1
      - msgpack==1.1.2
      - msgspec==0.19.0
      - msrest==0.7.1
      - multidict==6.7.0
      - multiprocess==0.70.18
      - mutagen==1.47.0
      - ninja==1.13.0
      - numba==0.61.2
      - numpy==2.2.6
      - numpy-financial==1.0.0
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cudnn-frontend==1.16.0
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-cutlass-dsl==4.2.1
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - oauth2client==4.1.3
      - oauthlib==3.3.1
      - odfpy==1.4.1
      - onnx==1.19.1
      - openai==2.6.1
      - openai-harmony==0.0.8
      - opencv-contrib-python==4.10.0.84
      - opencv-python-headless==4.12.0.88
      - openpyxl==3.1.5
      - opt-einsum==3.3.0
      - outlines-core==0.2.11
      - packaging==25.0
      - paddleocr==3.3.2
      - paddlepaddle==3.2.2
      - paddlex==3.3.9
      - pandas==2.2.3
      - paramiko==4.0.0
      - partial-json-parser==0.2.1.1.post6
      - pdfminer-six==20250506
      - pdfplumber==0.11.7
      - pillow==12.0.0
      - platformdirs==4.5.0
      - playwright==1.55.0
      - polars==1.35.2
      - polars-runtime-32==1.35.2
      - pooch==1.8.2
      - prettytable==3.17.0
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - psutil==5.9.8
      - py-cpuinfo==9.0.0
      - pyacoustid==1.3.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyautogui==0.9.54
      - pybase64==1.4.2
      - pyclipper==1.3.0.post6
      - pycountry==24.6.1
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pydantic-extra-types==2.10.6
      - pydrive==1.3.1
      - pyee==13.0.0
      - pygame==2.6.1
      - pygetwindow==0.0.9
      - pyjwt==2.10.1
      - pymsgbox==2.0.1
      - pymupdf==1.26.5
      - pynacl==1.6.0
      - pynput==1.7.8
      - pyparsing==3.2.5
      - pypdf==6.1.3
      - pypdf2==3.0.1
      - pypdfium2==4.30.0
      - pyperclip==1.11.0
      - pyrect==0.2.0
      - pyscreeze==1.0.1
      - python-bidi==0.6.7
      - python-dateutil==2.9.0.post0
      - python-doctr==1.0.0
      - python-docx==1.2.0
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - python-pptx==1.0.2
      - python-xlib==0.33
      - python3-xlib==0.15
      - pytweening==1.2.0
      - pytz==2024.2
      - pywavelets==1.8.0
      - pyyaml==6.0.2
      - pyzmq==27.1.0
      - rapidfuzz==3.14.1
      - ray==2.51.1
      - referencing==0.37.0
      - regex==2025.10.23
      - requests==2.32.5
      - requests-file==3.0.1
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich-toolkit==0.15.1
      - rignore==0.7.6
      - rpds-py==0.28.0
      - rsa==4.9.1
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.15
      - s3transfer==0.14.0
      - safetensors==0.6.2
      - schedula==1.5.66
      - scikit-learn==1.7.2
      - sentencepiece==0.2.1
      - sentry-sdk==2.42.1
      - setproctitle==1.3.7
      - shapely==2.1.2
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - soundfile==0.13.1
      - soupsieve==2.8
      - soxr==1.0.0
      - starlette==0.49.3
      - supervisor==4.3.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tldextract==5.3.0
      - tokenizers==0.22.1
      - tomli==2.3.0
      - torch==2.9.0
      - torchaudio==2.9.0
      - torchvision==0.24.0
      - tqdm==4.65.2
      - transformers==4.57.1
      - triton==3.5.0
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - tzlocal==5.3.1
      - ujson==5.11.0
      - ultralytics==8.3.229
      - ultralytics-thop==2.0.18
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - validators==0.35.0
      - vllm==0.11.1
      - wandb==0.22.2
      - watchfiles==1.1.1
      - wcwidth==0.2.14
      - websockets==15.0.1
      - wrapt==1.17.3
      - wrapt-timeout-decorator==1.5.1
      - xformers==0.0.33.post1
      - xgrammar==0.1.25
      - xlsxwriter==3.2.9
      - xmltodict==1.0.2
      - yarl==1.22.0

